### ISSUE TITLE
[Help]Get a connection error when building Frontend.

### ISSUE THREAD

**Issue by ramboly** [kernelci/kernelci-docker#13]
Hi,all

It is my first time to install kernelci/kernelci-docker, and i got a error below when execute “docker-compose build”, I  was inside a company network, a so I add "ARG http_proxy my_http_proxy, ARG https_proxy, my_https_proxy" in every Dockerfile,  below is my enviroment and error log,  could anyone give some hints?

**Error log:**
`Get:93 http://httpredir.debian.org/debian/ jessie/main python-pip all 1.5.6-5 [114 kB]
Get:94 http://httpredir.debian.org/debian/ jessie/main uwsgi-core amd64 2.0.7-1+deb8u2 [473 kB]
Get:95 http://httpredir.debian.org/debian/ jessie/main uwsgi-plugin-python amd64 2.0.7-1+deb8u2 [91.0 kB]
/nGet:96 http://security.debian.org/ jessie/updates/main gcc-4.9 amd64 4.9.2-10+deb8u2 [5373 kB]
/n/n/n/nTraceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 118, in perform_command
  File "compose/cli/main.py", line 239, in build
  File "compose/project.py", line 314, in build
  File "compose/service.py", line 892, in build
  File "compose/progress_stream.py", line 18, in stream_output
  File "compose/utils.py", line 58, in split_buffer
  File "compose/utils.py", line 34, in stream_as_text
  File "site-packages/docker/api/client.py", line 296, in _stream_helper
  File "site-packages/requests/packages/urllib3/response.py", line 324, in read
  File "contextlib.py", line 35, in __exit__
  File "site-packages/requests/packages/urllib3/response.py", line 250, in _error_catcher
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Failed to execute script docker-compos`

**uname -a:**
`Linux debian-test 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux`

**docker info:** 
Containers: 27
 Running: 5
 Paused: 0
 Stopped: 22
Images: 502
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /work/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15004
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: tq365bg9gbaghetjq82j74ni1
 Is Manager: true
 ClusterID: h68qqo8hpf28coefzumsfhamj
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: xx.xxx.xxx.xxx
 Manager Addresses:
  xx.xxx.xxx.xxx:xxx
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: b41633746ed4833f52c3c071e8edcfa2713e5677 (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux buster/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.642GiB
Name: debian-test
ID: 47VB:RWMH:OMSP:2F7P:HWPQ:NCHV:R4JD:N74J:6PUS:6JOR:DFA7:LQQM
Docker Root Dir: /work/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy:   xx.xxx.xxx.xxx:xxx
HTTPS Proxy:   xx.xxx.xxx.xxx:xxx
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Comment by khilman** [comment]
Could you try this fork of kernelci-docker to see if you have the same issues?  This main branch hasn't gotten much testing recently: https://github.com/lucj/kernelci-docker
